### ISSUE TITLE
Cannot find style files in my project. 

### ISSUE THREAD

**Issue by wrux** [exelban/stylelint#2]
I have setup the linter in a workflow action. With the default configuration it fails because it cannot find any .css files so I changed the configuration to look for scss file sand it still fails.

Here's my jobs: 
```
name: CI

on:
  push:
    branches:
    - master
    - feature/*
    - fix/*

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Style Lint
      uses: exelban/stylelint@master
      with:
        args: ./**/*.scss
```

Here's the output:
```
Run exelban/stylelint@master
/usr/bin/docker run --name bb8165570c4d792448e6971767005ebe8d22_5a7058 --label 04bb81 --workdir /github/workspace --rm -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/platformcraft/platformcraft":"/github/workspace" 04bb81:65570c4d792448e6971767005ebe8d22 ./**/*.scss
Error: No files matching the pattern "./**/*.scss" were found.
    at globby.then.filePaths (/github/workspace/node_modules/stylelint/lib/standalone.js:210:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
##[error]Docker run failed with exit code 1
```

**Comment by exelban** [comment]
@wrux are you sure that files exist?

**Comment by wrux** [comment]
Yes, heres an example: https://github.com/wrux/platformcraft/blob/master/src/sass/app.scss

**Comment by exelban** [comment]
@wrux according to [this](https://github.com/wrux/platformcraft/blob/master/.github/workflows/main.yml) workflow you don't checkout your project. So there is no .scss or .css files.

**Comment by wrux** [comment]
@exelban Oh great that worked now. Thank 👍
